CREATE TABLE IF NOT EXISTS attendees (
    id INT AUTO_INCREMENT PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    company VARCHAR(255) NOT NULL,
    companySize INT NOT NULL,
    jobTitle VARCHAR(255) NOT NULL,
    email VARCHAR(255) DEFAULT '',
    phone VARCHAR(50) DEFAULT '',
    interest TEXT NOT NULL,
    currentChallenge TEXT,
    pdpaConsent TINYINT(1) DEFAULT 0,
    assigned_team VARCHAR(100) DEFAULT 'Client Solutions Group (CSG)',
    action_recommendation TEXT,
    routing_status VARCHAR(50) DEFAULT 'ROUTED_AUTOMATICALLY',
    followup_note TEXT,
    visitCount INT DEFAULT 1,
    buying_intent VARCHAR(255) DEFAULT NULL, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_assigned_team (assigned_team),
    INDEX idx_token (token)
);ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;